services:
  - type: web
    name: environmental-monitoring
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://asusdibyajyoti:M4-QF-jANcwtzNP@cluster0.6isyaus.mongodb.net/environmental_monitoring?retryWrites=true&w=majority
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

databases:
  - name: environmental-monitoring-db
    databaseName: environmental_monitoring
    user: environmental_monitoring_user
    plan: free
